### ISSUE TITLE
Fetch module facts hash is empty value

### ISSUE THREAD

**Issue by nareshblu** [voxpupuli/puppet-wget#112]
It's failing in my system.
I got an error Evaluation Error: Operator '[]' is not applicable to an Undef Value. My facter version is 2.4.6
In my system, this manifest is not able to access the facter variables like $facts['var_name'].

Example:
$facts['os']['name'] is returning empty value in fetch.pp

**Comment by Dan33l** [comment]
Hi @nareshblu 

The module is declared as deprecated and we suggest `puppet-archive` as its replacement. I strongly recommend to migrate to this other module.
