### ISSUE TITLE
Archive this in favour of puppet/archive?

### ISSUE THREAD

**Issue by bastelfreak** [voxpupuli/puppet-wget#117]
Hi!

we've got our archive module that is perfectly for downloading files. I don't see any purpose in maintaining this module while we still have archive. Unless someone likes to keep this module, I'm going to archive it in the next weeks. @voxpupuli/collaborators please provide feedback :)

**Comment by dhollinger** [comment]
I'm all for this

**Comment by roidelapluie** [comment]
The readme already states: this module is declared as deprecated by Vox Pupuli.

**Comment by bastelfreak** [comment]
ah, we already marked it as deprecated https://forge.puppet.com/puppet/wget \o/

**Comment by alexjfisher** [comment]
FWIW, it's in my Puppetfile as a dependency of a nexus module I use. https://forge.puppet.com/hubspot/nexus/dependencies

**Comment by alexjfisher** [comment]
There's also https://github.com/hubspotdevops/puppet-nexus/issues/116...
